version: '3.7'

services:
  migration_db_up:
    image: migrate/migrate:v4.16.2
    command:
      [
        "-path", "/migrations",
        "-database" , "postgres://gophermart:RASKkCt3PVEU@docker.for.mac.localhost:5432/gophermart?sslmode=disable",
        "up"
        ]
    volumes:
      - ./db/migrations:/migrations
    
  

  migration_db_down:
    image: migrate/migrate:v4.16.2
    command:
      [
        "-path", "/migrations",
        "-database" , "postgres://gophermart:RASKkCt3PVEU@docker.for.mac.localhost:5432/gophermart?sslmode=disable",
        "down", "-all",
        ]
    volumes:
      - ./db/migrations:/migrations
    
    

  migration_db_force:
    image: migrate/migrate:v4.16.2
    command:
      [
        "-path", "/migrations",
        "-database" , "postgres://gophermart:RASKkCt3PVEU@docker.for.mac.localhost:5432/gophermart?sslmode=disable",
        "force", "3"
        ]
    volumes:
      - ./db/migrations:/migrations
    


  migration_db_add:
    image: migrate/migrate:v4.16.2
    command:
      [
        "create",
        "-dir", "/migrations",
        "-ext", ".sql",
        "-seq", "-digits", "5",
        "add_users"
      ]
    volumes:
      - ./db/migrations:/migrations
